name: Test workflow

on:
  push:
  
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependancies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build-test # permet de definir que le Job nommé doit fonctionner avant de lancer celui là

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: "herokuclci" #Must be unique in Heroku
          heroku_email: "toure.ipro@gmail.com"